CREATE TABLE b_crm_lead
(
	ID INT (18) UNSIGNED NOT NULL AUTO_INCREMENT,
	DATE_CREATE DATETIME DEFAULT '0000-00-00 00:00:00',
	DATE_MODIFY DATETIME DEFAULT '0000-00-00 00:00:00',
	CREATED_BY_ID INT (18) UNSIGNED NOT NULL,
	MODIFY_BY_ID INT (18) UNSIGNED DEFAULT NULL,
	ASSIGNED_BY_ID INT (18) UNSIGNED DEFAULT NULL,
	OPENED CHAR(1) DEFAULT 'N',
	COMPANY_ID INT (18) UNSIGNED DEFAULT NULL,
	CONTACT_ID INT (18) UNSIGNED DEFAULT NULL,
	STATUS_ID VARCHAR (50) DEFAULT NULL,
	STATUS_DESCRIPTION TEXT DEFAULT NULL,
	PRODUCT_ID VARCHAR (50) DEFAULT NULL,
	OPPORTUNITY DECIMAL(18,2) DEFAULT NULL,
	CURRENCY_ID VARCHAR (50) DEFAULT NULL,
	OPPORTUNITY_ACCOUNT DECIMAL(18,2) DEFAULT NULL,
	ACCOUNT_CURRENCY_ID VARCHAR (50) DEFAULT NULL,
	SOURCE_ID VARCHAR (50) DEFAULT NULL,
	SOURCE_DESCRIPTION TEXT DEFAULT NULL,
	TITLE VARCHAR (255) DEFAULT NULL,
	FULL_NAME VARCHAR (100) DEFAULT NULL,
	NAME VARCHAR (50) DEFAULT NULL,
	LAST_NAME VARCHAR (50) DEFAULT NULL,
	SECOND_NAME VARCHAR (50) DEFAULT NULL,
	COMPANY_TITLE VARCHAR (255) DEFAULT NULL,
	POST VARCHAR (255) DEFAULT NULL,
	ADDRESS TEXT DEFAULT NULL,
	COMMENTS TEXT DEFAULT NULL,
	EXCH_RATE DECIMAL(18,2) DEFAULT 1,
	ORIGINATOR_ID VARCHAR(255) NULL,
	ORIGIN_ID VARCHAR(255) NULL,
	DATE_CLOSED DATETIME NULL,
	BIRTHDATE DATE NULL,
	BIRTHDAY_SORT INT(1) NOT NULL DEFAULT 1024,
	PRIMARY KEY (ID),
	INDEX IX_LEAD_FULL_NAME (FULL_NAME),
	INDEX IX_LEAD_1 (STATUS_ID, ASSIGNED_BY_ID),
	INDEX IX_LEAD_2 (DATE_MODIFY),
	INDEX IX_LEAD_3 (CONTACT_ID),
	INDEX IX_LEAD_4 (COMPANY_ID),
	INDEX IX_LEAD_5 (BIRTHDAY_SORT, ID),
	INDEX IX_LEAD_6 (BIRTHDATE, ID)
);

CREATE TABLE b_crm_deal
(
	ID INT (18) UNSIGNED NOT NULL AUTO_INCREMENT,
	DATE_CREATE DATETIME DEFAULT '0000-00-00 00:00:00',
	DATE_MODIFY DATETIME DEFAULT '0000-00-00 00:00:00',
	CREATED_BY_ID INT (18) UNSIGNED NOT NULL,
	MODIFY_BY_ID INT (18) UNSIGNED DEFAULT NULL,
	ASSIGNED_BY_ID INT (18) UNSIGNED DEFAULT NULL,
	OPENED CHAR(1) DEFAULT 'N',
	LEAD_ID INT (18) DEFAULT NULL,
	COMPANY_ID INT (18) UNSIGNED DEFAULT NULL,
	CONTACT_ID INT (18) UNSIGNED DEFAULT NULL,
	TITLE VARCHAR (255) DEFAULT NULL,
	PRODUCT_ID VARCHAR (50) DEFAULT NULL,
	STAGE_ID VARCHAR (50) DEFAULT NULL,
	CLOSED CHAR (1) DEFAULT 'N',
	TYPE_ID VARCHAR (50) DEFAULT NULL,
	OPPORTUNITY DECIMAL(18,2) DEFAULT NULL,
	TAX_VALUE DECIMAL(18,2) DEFAULT NULL,
	CURRENCY_ID VARCHAR (50) DEFAULT NULL,
	OPPORTUNITY_ACCOUNT DECIMAL(18,2) DEFAULT NULL,
	TAX_VALUE_ACCOUNT DECIMAL(18,2) DEFAULT NULL,
	ACCOUNT_CURRENCY_ID VARCHAR (50) DEFAULT NULL,
	PROBABILITY TINYINT (3) DEFAULT NULL,
	COMMENTS TEXT DEFAULT NULL,
	BEGINDATE DATETIME DEFAULT NULL,
	CLOSEDATE DATETIME DEFAULT NULL,
	EVENT_DATE DATETIME NULL,
	EVENT_ID varchar(50) NULL,
	EVENT_DESCRIPTION text NULL,
	EXCH_RATE DECIMAL(18,2) DEFAULT 1,
	LOCATION_ID varchar(100) NULL,
	ORIGINATOR_ID VARCHAR(255) NULL,
	ORIGIN_ID VARCHAR(255) NULL,
	ADDITIONAL_INFO TEXT NULL,
	PRIMARY KEY (ID),
	INDEX IX_DEAL_1 (STAGE_ID, ASSIGNED_BY_ID),
	INDEX IX_DEAL_2 (COMPANY_ID),
	INDEX IX_DEAL_3 (CONTACT_ID)
);

CREATE TABLE b_crm_contact
(
	ID INT (18) UNSIGNED NOT NULL AUTO_INCREMENT,
	DATE_CREATE DATETIME DEFAULT '0000-00-00 00:00:00',
	DATE_MODIFY DATETIME DEFAULT '0000-00-00 00:00:00',
	CREATED_BY_ID INT (18) UNSIGNED NOT NULL,
	MODIFY_BY_ID INT (18) UNSIGNED DEFAULT NULL,
	ASSIGNED_BY_ID INT (18) UNSIGNED DEFAULT NULL,
	OPENED CHAR(1) DEFAULT 'N',
	COMPANY_ID INT (18) UNSIGNED DEFAULT NULL,
	SOURCE_ID VARCHAR (50) DEFAULT NULL,
	SOURCE_DESCRIPTION TEXT DEFAULT NULL,
	FULL_NAME VARCHAR (100) DEFAULT NULL,
	NAME VARCHAR (50) DEFAULT NULL,
	LAST_NAME VARCHAR (50) DEFAULT NULL,
	SECOND_NAME VARCHAR (50) DEFAULT NULL,
	PHOTO VARCHAR (10) DEFAULT NULL,
	POST VARCHAR (255) DEFAULT NULL,
	ADDRESS TEXT DEFAULT NULL,
	COMMENTS TEXT DEFAULT NULL,
	LEAD_ID INT (18) DEFAULT NULL,
	EXPORT CHAR (1) DEFAULT 'N',
	TYPE_ID VARCHAR (50) DEFAULT NULL,
	ORIGINATOR_ID VARCHAR(255) NULL,
	ORIGIN_ID VARCHAR(255) NULL,
	BIRTHDATE DATE DEFAULT NULL,
	BIRTHDAY_SORT INT(1) NOT NULL DEFAULT 1024,
	PRIMARY KEY (ID),
	INDEX IX_CONTACT_LAST_NAME (NAME),
	INDEX IX_CONTACT_NAME (LAST_NAME),
	INDEX IX_CONTACT_FULL_NAME (FULL_NAME),
	INDEX IX_CONTACT_BDAY (BIRTHDAY_SORT, ID),
	INDEX IX_CONTACT_BDATE (BIRTHDATE, ID)
);

CREATE TABLE b_crm_company
(
	ID INT (18) UNSIGNED NOT NULL AUTO_INCREMENT,
	DATE_CREATE DATETIME DEFAULT '0000-00-00 00:00:00',
	DATE_MODIFY DATETIME DEFAULT '0000-00-00 00:00:00',
	CREATED_BY_ID INT (18) UNSIGNED NOT NULL,
	MODIFY_BY_ID INT (18) UNSIGNED DEFAULT NULL,
	ASSIGNED_BY_ID INT (1) UNSIGNED DEFAULT NULL,
	OPENED CHAR(1) DEFAULT 'N',
	TITLE varchar(255) DEFAULT NULL,
	LOGO VARCHAR (10) DEFAULT NULL,
	ADDRESS text DEFAULT NULL,
	ADDRESS_LEGAL text DEFAULT NULL,
	BANKING_DETAILS text DEFAULT NULL,
	COMMENTS text DEFAULT NULL,
	COMPANY_TYPE varchar(50) DEFAULT NULL,
	INDUSTRY varchar(50) DEFAULT NULL,
	REVENUE varchar(255) DEFAULT NULL,
	CURRENCY_ID varchar(50) DEFAULT NULL,
	EMPLOYEES varchar(50) DEFAULT NULL,
	LEAD_ID int(18) DEFAULT NULL,
	ORIGINATOR_ID VARCHAR(255) NULL,
	ORIGIN_ID VARCHAR(255) NULL,
	PRIMARY KEY  (ID),
	KEY IX_COMPANY_TITLE (TITLE)
);

CREATE TABLE b_crm_status
(
	ID INT (18) NOT NULL AUTO_INCREMENT,
	ENTITY_ID VARCHAR (50) NOT NULL,
	STATUS_ID VARCHAR (50) NOT NULL,
	NAME VARCHAR (100) NOT NULL,
	NAME_INIT VARCHAR (100) NULL,
	SORT INT (18) NOT NULL,
	SYSTEM CHAR (1) NOT NULL,
	PRIMARY KEY (ID),
	INDEX IX_B_CRM_STATUS (STATUS_ID, ENTITY_ID)
);

CREATE TABLE b_crm_field_multi
(
	ID int(18) NOT NULL auto_increment,
	ENTITY_ID VARCHAR (16) NOT NULL,
	ELEMENT_ID int(18) NOT NULL,
	TYPE_ID VARCHAR (16) NOT NULL,
	VALUE_TYPE VARCHAR (50) NOT NULL,
	COMPLEX_ID  VARCHAR(100) NOT NULL,
	VALUE VARCHAR (250) NOT NULL,
	PRIMARY KEY  (ID),
	KEY IX_FM_ENTITY_ELEMENT (ENTITY_ID, ELEMENT_ID),
	KEY IX_B_CRM_FM_2 (ENTITY_ID, TYPE_ID, ELEMENT_ID, ID),
	KEY IX_B_CRM_FM_3 (TYPE_ID, VALUE, ENTITY_ID, ELEMENT_ID)
);

CREATE TABLE b_crm_event
(
	ID int(18) NOT NULL auto_increment,
	DATE_CREATE datetime NOT NULL,
	CREATED_BY_ID int(18) NOT NULL,
	EVENT_ID varchar(50) NULL,
	EVENT_NAME varchar(255) NOT NULL,
	EVENT_TEXT_1 text NULL,
	EVENT_TEXT_2 text NULL,
	EVENT_TYPE int(11) NULL,
	FILES text NULL,
	PRIMARY KEY  (ID),
	INDEX IX_EVENT_1 (DATE_CREATE),
	INDEX IX_B_CRM_EVENT_2 (EVENT_TYPE, EVENT_ID, ID)
);

CREATE TABLE b_crm_event_relations
(
	ID int(18) NOT NULL auto_increment,
	ASSIGNED_BY_ID int(18) NOT NULL,
	ENTITY_TYPE varchar(50) NULL,
	ENTITY_ID int(11) NOT NULL,
	ENTITY_FIELD varchar(255) NULL,
	EVENT_ID int(18) NOT NULL,
	PRIMARY KEY  (ID),
	KEY IX_EVENT_REL_ENTITY (ENTITY_TYPE, ENTITY_ID, ENTITY_FIELD),
	INDEX IX_EVENT_REL_1 (EVENT_ID)
);

CREATE TABLE b_crm_entity_lock
(
	ENTITY_ID INT (11) NOT NULL,
	ENTITY_TYPE VARCHAR (10) NOT NULL,
	DATE_LOCK DATETIME DEFAULT NULL,
	LOCKED_BY VARCHAR (32) DEFAULT NULL,
	PRIMARY KEY (ENTITY_ID)
);

CREATE TABLE b_crm_entity_perms
(
	ID INT(18) UNSIGNED NOT NULL AUTO_INCREMENT,
	ENTITY VARCHAR(20) NOT NULL,
	ENTITY_ID INT(18) NOT NULL,
	ATTR VARCHAR(30) NOT NULL,
	PRIMARY KEY (ID),
	INDEX IX_ENTITY_ATTR (ENTITY, ENTITY_ID, ATTR),
	INDEX IX_ENTITY_ATTR_1(ENTITY, ATTR, ENTITY_ID)
);

CREATE TABLE b_crm_role
(
	ID INT(18) UNSIGNED NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE b_crm_role_perms
(
	ID INT(18) UNSIGNED NOT NULL AUTO_INCREMENT,
	ROLE_ID INT(18) UNSIGNED NOT NULL,
	ENTITY VARCHAR(20) NOT NULL,
	FIELD VARCHAR(30) DEFAULT '-',
	FIELD_VALUE VARCHAR(255) DEFAULT NULL,
	PERM_TYPE VARCHAR(20) NOT NULL,
	ATTR CHAR(1) DEFAULT '',
	PRIMARY KEY (ID),
	INDEX IX_ROLE_ID (ROLE_ID)
);

CREATE TABLE b_crm_role_relation
(
	ID INT(18) NOT NULL AUTO_INCREMENT,
	ROLE_ID INT(18) UNSIGNED NOT NULL,
	RELATION VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID),
	INDEX IX_ROLE_RELATION (ROLE_ID, RELATION)
);

CREATE TABLE IF NOT EXISTS b_crm_external_sale
(
	ID INT(18) NOT NULL AUTO_INCREMENT,
	ACTIVE CHAR(1) NOT NULL DEFAULT 'Y',
	DATE_CREATE datetime NOT NULL,
	DATE_UPDATE datetime NOT NULL,
	NAME VARCHAR(128) NULL,
	SCHEME VARCHAR(5) NOT NULL DEFAULT 'http',
	SERVER VARCHAR(192) NOT NULL,
	PORT INT(18) NOT NULL DEFAULT 80,
	LOGIN VARCHAR(64) NOT NULL,
	PASSWORD VARCHAR(128) NOT NULL,
	MODIFICATION_LABEL INT(18) NULL,
	IMPORT_SIZE INT(18) NULL,
	IMPORT_PERIOD INT(18) NULL,
	IMPORT_PROBABILITY INT(18) NULL,
	IMPORT_RESPONSIBLE INT(18) NULL,
	IMPORT_PUBLIC char(1) NULL,
	IMPORT_PREFIX VARCHAR(128) NULL,
	IMPORT_ERRORS INT(18) NULL,
	IMPORT_GROUP_ID INT(18) NULL,
	COOKIE TEXT NULL,
	LAST_STATUS TEXT NULL,
	LAST_STATUS_DATE datetime NULL,
	SYNC_DATA TEXT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS b_crm_catalog
(
	ID INT(1) NOT NULL,
	ORIGINATOR_ID VARCHAR(255) NULL,
	ORIGIN_ID VARCHAR(255) NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS b_crm_product
(
	ID INT(1) NOT NULL,
	CATALOG_ID INT(1) NOT NULL,
	CURRENCY_ID VARCHAR(50) NOT NULL,
	PRICE DECIMAL(18,2) NOT NULL DEFAULT 0,
	ORIGINATOR_ID VARCHAR(255) NULL,
	ORIGIN_ID VARCHAR(255) NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS b_crm_product_row
(
	ID INT(18) UNSIGNED NOT NULL AUTO_INCREMENT,
	OWNER_ID INT(1) NOT NULL,
	OWNER_TYPE CHAR(3) NOT NULL,
	PRODUCT_ID INT(1) NOT NULL,
	PRODUCT_NAME VARCHAR(256) NULL,
	PRICE DECIMAL(18,2) NOT NULL,
	PRICE_ACCOUNT DECIMAL(18,2) NOT NULL DEFAULT 0,
	QUANTITY DECIMAL(18,4) NOT NULL,
	DISCOUNT_TYPE_ID TINYINT(1) UNSIGNED NULL,
	DISCOUNT_RATE DECIMAL(18,2) NULL,
	DISCOUNT_SUM DECIMAL(18,2) NULL,
	TAX_RATE DECIMAL(18,2) NULL,
	TAX_INCLUDED CHAR(1) NULL,
	CUSTOMIZED CHAR(1) NULL,
	MEASURE_CODE INT(1) UNSIGNED NULL,
	MEASURE_NAME VARCHAR(50) NULL,
	SORT INT(1) NULL,
	PRIMARY KEY(ID),
	INDEX IX_B_CRM_PROD_ROW_1(OWNER_ID, OWNER_TYPE, SORT, ID)
);

CREATE TABLE IF NOT EXISTS b_crm_product_row_cfg(
	OWNER_ID INT(1) NOT NULL,
	OWNER_TYPE CHAR(3) NOT NULL,
	SETTINGS TEXT,
	PRIMARY KEY(OWNER_ID, OWNER_TYPE)
);

CREATE TABLE IF NOT EXISTS b_crm_act(
	ID INT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
	TYPE_ID TINYINT(1) UNSIGNED NOT NULL,
	OWNER_ID INT(1) NOT NULL,
	OWNER_TYPE_ID TINYINT(1) UNSIGNED NOT NULL,
	ASSOCIATED_ENTITY_ID INT(1),
	SUBJECT VARCHAR(512) NOT NULL,
	COMPLETED CHAR(1) NOT NULL DEFAULT 'N',
	RESPONSIBLE_ID INT(1) NOT NULL,
	PRIORITY INT(1) NOT NULL,
	NOTIFY_TYPE INT(1) NOT NULL,
	NOTIFY_VALUE INT(1) UNSIGNED,
	DESCRIPTION LONGTEXT NULL,
	DESCRIPTION_TYPE TINYINT(1) UNSIGNED NULL,
	DIRECTION TINYINT(1) UNSIGNED NOT NULL,
	LOCATION VARCHAR(256),
	CREATED DATETIME NOT NULL,
	LAST_UPDATED DATETIME NOT NULL,
	START_TIME DATETIME,
	END_TIME DATETIME,
	DEADLINE DATETIME,
	STORAGE_TYPE_ID TINYINT(1) UNSIGNED NULL,
	STORAGE_ELEMENT_IDS TEXT NULL,
	PARENT_ID INT(1) UNSIGNED NOT NULL DEFAULT 0,
	URN VARCHAR(64) NULL,
	SETTINGS TEXT NULL,
	ORIGIN_ID VARCHAR(255) NULL,
	AUTHOR_ID INT(1) UNSIGNED NULL,
	EDITOR_ID INT(1) UNSIGNED NULL,
	PRIMARY KEY(ID),
	INDEX IX_B_CRM_ACT(ID, PARENT_ID, OWNER_ID, OWNER_TYPE_ID),
	INDEX IX_B_CRM_ACT_1(RESPONSIBLE_ID, COMPLETED, DEADLINE),
	INDEX IX_B_CRM_ACT_2 (ASSOCIATED_ENTITY_ID, TYPE_ID),
	INDEX IX_B_CRM_ACT_4 (DEADLINE),
	INDEX IX_B_CRM_ACT_5 (ORIGIN_ID),
	INDEX IX_B_CRM_ACT_6 (TYPE_ID, COMPLETED, DEADLINE, ID)
);

CREATE TABLE IF NOT EXISTS b_crm_act_bind(
	ID INT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
	ACTIVITY_ID INT(1) NOT NULL,
	OWNER_ID INT(1) NOT NULL,
	OWNER_TYPE_ID TINYINT(1) UNSIGNED NOT NULL,
	PRIMARY KEY(ID),
	INDEX IX_B_CRM_ACT_BIND_1(ACTIVITY_ID),
	INDEX IX_B_CRM_ACT_BIND_2(OWNER_ID, OWNER_TYPE_ID, ACTIVITY_ID)
);

CREATE TABLE IF NOT EXISTS b_crm_act_comm(
	ID INT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
	ACTIVITY_ID INT(1) UNSIGNED NOT NULL,
	OWNER_ID INT(1) NOT NULL,
	OWNER_TYPE_ID TINYINT(1) UNSIGNED NOT NULL,
	TYPE VARCHAR(64),
	VALUE VARCHAR(256),
	ENTITY_ID INT(1) UNSIGNED NOT NULL,
	ENTITY_TYPE_ID TINYINT(1) UNSIGNED NOT NULL,
	ENTITY_SETTINGS TEXT,
	PRIMARY KEY(ID),
	INDEX IX_B_CRM_ACT_COMM(ACTIVITY_ID, OWNER_ID, OWNER_TYPE_ID, ENTITY_ID, ENTITY_TYPE_ID)
);

CREATE TABLE IF NOT EXISTS b_crm_act_elem(
	ACTIVITY_ID INT(1) UNSIGNED NOT NULL,
	STORAGE_TYPE_ID TINYINT(1) UNSIGNED NOT NULL,
	ELEMENT_ID INT(1) UNSIGNED NOT NULL,
	PRIMARY KEY(ACTIVITY_ID, STORAGE_TYPE_ID, ELEMENT_ID)
);

CREATE TABLE IF NOT EXISTS b_crm_usr_act(
	USER_ID INT(1) UNSIGNED NOT NULL,
	OWNER_ID INT(1) NOT NULL,
	OWNER_TYPE_ID TINYINT(1) UNSIGNED NOT NULL,
	ACTIVITY_TIME DATETIME NOT NULL,
	ACTIVITY_ID INT(1) UNSIGNED NOT NULL,
	DEPARTMENT_ID INT(1) UNSIGNED NOT NULL,
	SORT VARCHAR(16) NULL,
	PRIMARY KEY(USER_ID, OWNER_ID, OWNER_TYPE_ID),
	INDEX IX_B_CRM_USR_ACT(USER_ID, OWNER_ID, OWNER_TYPE_ID, ACTIVITY_TIME, ACTIVITY_ID, DEPARTMENT_ID),
	INDEX IX_B_CRM_USR_ACT_2 (OWNER_ID ASC, OWNER_TYPE_ID ASC, USER_ID DESC, SORT DESC)
);

CREATE TABLE IF NOT EXISTS b_crm_usr_mt(
	ID INT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
	OWNER_ID INT(1) NOT NULL,
	ENTITY_TYPE_ID TINYINT(1) UNSIGNED NOT NULL,
	SCOPE TINYINT(1) UNSIGNED NOT NULL,
	IS_ACTIVE CHAR(1) NOT NULL DEFAULT 'N',
	TITLE VARCHAR(128),
	EMAIL_FROM VARCHAR(255),
	SUBJECT VARCHAR(255),
	BODY TEXT,
	SING_REQUIRED CHAR(1) NOT NULL DEFAULT 'N',
	SORT INT(1) NOT NULL DEFAULT 100,
	CREATED DATETIME NOT NULL,
	LAST_UPDATED DATETIME NOT NULL,
	AUTHOR_ID INT(1) UNSIGNED NOT NULL,
	EDITOR_ID INT(1) UNSIGNED NOT NULL,
	PRIMARY KEY(ID),
	INDEX IX_B_CRM_USR_MT(OWNER_ID, ENTITY_TYPE_ID, SCOPE, IS_ACTIVE)
);

CREATE TABLE IF NOT EXISTS b_crm_sl_rel(
	SL_ID INT NOT NULL,
	SL_EVENT_ID VARCHAR(50) NOT NULL,
	SL_ENTITY_TYPE VARCHAR(50) NOT NULL,
	SL_LAST_UPDATED DATETIME,
	ENTITY_ID INT(1) UNSIGNED NOT NULL,
	SL_PARENT_ENTITY_TYPE VARCHAR(50) NOT NULL,
	PARENT_ENTITY_ID INT(1) UNSIGNED NOT NULL,
	LVL TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
	TYPE_ID TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
	INDEX IX_B_CRM_SL_REL_1(SL_PARENT_ENTITY_TYPE, PARENT_ENTITY_ID, LVL, SL_ENTITY_TYPE, SL_EVENT_ID, SL_ID),
	INDEX IX_B_CRM_SL_REL_2(SL_ENTITY_TYPE, ENTITY_ID),
	INDEX IX_B_CRM_SL_REL_3(SL_ID, TYPE_ID),
	INDEX IX_B_CRM_SL_REL_4(SL_LAST_UPDATED, SL_PARENT_ENTITY_TYPE, PARENT_ENTITY_ID, LVL, SL_ENTITY_TYPE, SL_EVENT_ID, SL_ID)
);

CREATE TABLE IF NOT EXISTS b_crm_sl_subscr(
	USER_ID INT(1) UNSIGNED NOT NULL,
	SL_ENTITY_TYPE VARCHAR(50) NOT NULL,
	ENTITY_ID INT(1) UNSIGNED NOT NULL,
	TYPE_ID TINYINT(1) UNSIGNED NOT NULL,
	PRIMARY KEY(USER_ID, SL_ENTITY_TYPE, ENTITY_ID, TYPE_ID),
	INDEX IX_B_CRM_SL_SUBSCR_1(SL_ENTITY_TYPE, ENTITY_ID, TYPE_ID)
);

CREATE TABLE IF NOT EXISTS b_crm_biz_type(
	CODE VARCHAR(32) NOT NULL,
	NAME VARCHAR(256) NOT NULL,
	LANG VARCHAR(2),
	PRIMARY KEY(CODE)
);

CREATE TABLE IF NOT EXISTS b_crm_dp_org_mcd(
	ID INT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
	ENTITY_TYPE_ID TINYINT(1) UNSIGNED NOT NULL,
	ENTITY_ID INT(1) UNSIGNED NOT NULL,
	TITLE VARCHAR(256) NOT NULL,
	PRIMARY KEY(ID),
	INDEX IX_B_CRM_DP_ORG_MCD_1(TITLE, ENTITY_TYPE_ID, ENTITY_ID, ID),
	INDEX IX_B_CRM_DP_ORG_MCD_2(ENTITY_TYPE_ID, ENTITY_ID, ID)
);

CREATE TABLE IF NOT EXISTS b_crm_dp_comm_mcd(
	ID INT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
	ENTITY_TYPE_ID TINYINT(1) UNSIGNED NOT NULL,
	ENTITY_ID INT(1) UNSIGNED NOT NULL,
	TYPE VARCHAR(32) NOT NULL,
	VALUE VARCHAR(256) NOT NULL,
	PRIMARY KEY(ID),
	INDEX IX_B_CRM_DP_COMM_MCD_1(TYPE, VALUE, ENTITY_TYPE_ID, ENTITY_ID, ID),
	INDEX IX_B_CRM_DP_COMM_MCD_2(ENTITY_TYPE_ID, ENTITY_ID, TYPE, ID)
);

CREATE TABLE IF NOT EXISTS b_crm_dp_prsn_mcd(
	ID INT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
	ENTITY_TYPE_ID TINYINT(1) UNSIGNED NOT NULL,
	ENTITY_ID INT(1) UNSIGNED NOT NULL,
	LAST_NAME VARCHAR (64) NOT NULL,
	NAME VARCHAR (64),
	SECOND_NAME VARCHAR (64),
	PRIMARY KEY(ID),
	INDEX IX_B_CRM_DP_PRSN_MCD_1(LAST_NAME, NAME, SECOND_NAME, ENTITY_TYPE_ID, ENTITY_ID, ID),
	INDEX IX_B_CRM_DP_PRSN_MCD_2(ENTITY_TYPE_ID, ENTITY_ID, ID),
	INDEX IX_B_CRM_DP_PRSN_MCD_3(LAST_NAME, ENTITY_TYPE_ID, ENTITY_ID, NAME, SECOND_NAME, ID),
	INDEX IX_B_CRM_DP_PRSN_MCD_4(ENTITY_TYPE_ID, ENTITY_ID, LAST_NAME, NAME, SECOND_NAME, ID),
	INDEX IX_B_CRM_DP_PRSN_MCD_5(ENTITY_TYPE_ID, LAST_NAME, NAME, SECOND_NAME)
);

CREATE TABLE IF NOT EXISTS b_crm_quote
(
	ID INT(18) UNSIGNED NOT NULL AUTO_INCREMENT,
	DATE_CREATE DATETIME NOT NULL,
	DATE_MODIFY DATETIME NOT NULL,
	CREATED_BY_ID INT(18) UNSIGNED NOT NULL,
	MODIFY_BY_ID INT(18) UNSIGNED DEFAULT NULL,
	ASSIGNED_BY_ID INT(18) UNSIGNED DEFAULT NULL,
	OPENED CHAR(1) DEFAULT 'N',
	LEAD_ID INT(18) UNSIGNED DEFAULT NULL,
	DEAL_ID INT(18) UNSIGNED DEFAULT NULL,
	COMPANY_ID INT(18) UNSIGNED DEFAULT NULL,
	CONTACT_ID INT(18) UNSIGNED DEFAULT NULL,
	PERSON_TYPE_ID INT NOT NULL,
	TITLE VARCHAR(255) DEFAULT NULL,
	STATUS_ID VARCHAR(50) DEFAULT NULL,
	CLOSED CHAR(1) DEFAULT 'N',
	OPPORTUNITY DECIMAL(18,2) DEFAULT NULL,
	TAX_VALUE DECIMAL(18,2) DEFAULT NULL,
	CURRENCY_ID VARCHAR(50) DEFAULT NULL,
	OPPORTUNITY_ACCOUNT DECIMAL(18,2) DEFAULT NULL,
	TAX_VALUE_ACCOUNT DECIMAL(18,2) DEFAULT NULL,
	ACCOUNT_CURRENCY_ID VARCHAR(50) DEFAULT NULL,
	COMMENTS TEXT DEFAULT NULL,
	COMMENTS_TYPE TINYINT(1) UNSIGNED NULL,
	BEGINDATE DATETIME,
	CLOSEDATE DATETIME,
	EXCH_RATE DECIMAL(18,2) DEFAULT 1,
	QUOTE_NUMBER VARCHAR(100) null,
	CONTENT TEXT DEFAULT NULL,
	CONTENT_TYPE TINYINT(1) UNSIGNED NULL,
	TERMS TEXT DEFAULT NULL,
	TERMS_TYPE TINYINT(1) UNSIGNED NULL,
	STORAGE_TYPE_ID TINYINT(1) UNSIGNED NULL,
	STORAGE_ELEMENT_IDS TEXT NULL,
	LOCATION_ID varchar(100) NULL,
	CLIENT_TITLE VARCHAR(255) NULL,
	CLIENT_ADDR VARCHAR(255) NULL,
	CLIENT_CONTACT VARCHAR(255) NULL,
	CLIENT_EMAIL VARCHAR(255) NULL,
	CLIENT_PHONE VARCHAR(255) NULL,
	CLIENT_TP_ID VARCHAR(255) NULL,
	CLIENT_TPA_ID VARCHAR(255) NULL,
	PRIMARY KEY (ID),
	INDEX IX_QUOTE_1 (STATUS_ID, ASSIGNED_BY_ID),
	INDEX IX_QUOTE_2 (COMPANY_ID),
	INDEX IX_QUOTE_3 (CONTACT_ID),
	INDEX IX_QUOTE_4 (DEAL_ID),
	INDEX IX_QUOTE_5 (LEAD_ID),
	UNIQUE IXS_QUOTE_NUMBER(QUOTE_NUMBER)
);

CREATE TABLE IF NOT EXISTS b_crm_quote_elem(
	QUOTE_ID INT(1) UNSIGNED NOT NULL,
	STORAGE_TYPE_ID TINYINT(1) UNSIGNED NOT NULL,
	ELEMENT_ID INT(1) UNSIGNED NOT NULL,
	PRIMARY KEY(QUOTE_ID, STORAGE_TYPE_ID, ELEMENT_ID)
);

CREATE TABLE IF NOT EXISTS b_crm_dp_index(
	USER_ID INT(1) UNSIGNED NOT NULL,
	ENTITY_TYPE_ID TINYINT(1) UNSIGNED NOT NULL,
	TYPE_ID TINYINT(1) UNSIGNED NOT NULL,
	MATCH_HASH VARCHAR(32) NOT NULL,
	MATCHES TEXT NULL,
	QUANTITY INT(1) UNSIGNED NOT NULL,
	ROOT_ENTITY_ID INT(1) UNSIGNED NOT NULL,
	ROOT_ENTITY_NAME_FLAG CHAR(1) NOT NULL,
	ROOT_ENTITY_NAME VARCHAR(256) NOT NULL,
	ROOT_ENTITY_TITLE_FLAG CHAR(1) NOT NULL,
	ROOT_ENTITY_TITLE VARCHAR(256) NOT NULL,
	ROOT_ENTITY_PHONE_FLAG CHAR(1) NOT NULL,
	ROOT_ENTITY_PHONE VARCHAR(256) NOT NULL,
	ROOT_ENTITY_EMAIL_FLAG CHAR(1) NOT NULL,
	ROOT_ENTITY_EMAIL VARCHAR(256) NOT NULL,
	IS_JUNK CHAR(1) NULL,
	PRIMARY KEY(USER_ID, ENTITY_TYPE_ID, TYPE_ID, MATCH_HASH),
	INDEX IX_B_CRM_DP_IND_1(USER_ID, ENTITY_TYPE_ID, ROOT_ENTITY_NAME_FLAG, ROOT_ENTITY_NAME, TYPE_ID),
	INDEX IX_B_CRM_DP_IND_2(USER_ID, ENTITY_TYPE_ID, ROOT_ENTITY_TITLE_FLAG, ROOT_ENTITY_TITLE, TYPE_ID),
	INDEX IX_B_CRM_DP_IND_3(USER_ID, ENTITY_TYPE_ID, ROOT_ENTITY_PHONE_FLAG, ROOT_ENTITY_PHONE, TYPE_ID),
	INDEX IX_B_CRM_DP_IND_4(USER_ID, ENTITY_TYPE_ID, ROOT_ENTITY_EMAIL_FLAG, ROOT_ENTITY_EMAIL, TYPE_ID),
	INDEX IX_B_CRM_DP_IND_5(MATCH_HASH, TYPE_ID, ENTITY_TYPE_ID),
	INDEX IX_B_CRM_DP_IND_6(ROOT_ENTITY_ID, ENTITY_TYPE_ID)
);

CREATE TABLE IF NOT EXISTS b_crm_dp_index_mismatch(
	USER_ID INT(1) UNSIGNED NOT NULL,
	ENTITY_TYPE_ID TINYINT(1) UNSIGNED NOT NULL,
	TYPE_ID TINYINT(1) UNSIGNED NOT NULL,
	MATCH_HASH VARCHAR(32) NOT NULL,
	L_ENTITY_ID INT(1) UNSIGNED NOT NULL,
	R_ENTITY_ID INT(1) UNSIGNED NOT NULL,
	PRIMARY KEY(USER_ID, ENTITY_TYPE_ID, TYPE_ID, MATCH_HASH, L_ENTITY_ID, R_ENTITY_ID),
	INDEX IX_B_CRM_DP_IND_MISM_1(L_ENTITY_ID, ENTITY_TYPE_ID),
	INDEX IX_B_CRM_DP_IND_MISM_2(R_ENTITY_ID, ENTITY_TYPE_ID)
);

CREATE TABLE IF NOT EXISTS b_crm_dp_entity_stat(
	ENTITY_ID INT(1) UNSIGNED NOT NULL,
	ENTITY_TYPE_ID TINYINT(1) UNSIGNED NOT NULL,
	RANKING_DATA VARCHAR(512) NULL,
	PRIMARY KEY(ENTITY_ID, ENTITY_TYPE_ID)
);

CREATE TABLE IF NOT EXISTS b_crm_dp_entity_hash(
	ENTITY_ID INT(1) UNSIGNED NOT NULL,
	ENTITY_TYPE_ID TINYINT(1) UNSIGNED NOT NULL,
	TYPE_ID TINYINT(1) UNSIGNED NOT NULL,
	MATCH_HASH VARCHAR(32) NOT NULL,
	IS_PRIMARY CHAR(1) NOT NULL,
	PRIMARY KEY(ENTITY_ID, ENTITY_TYPE_ID, TYPE_ID, MATCH_HASH),
	INDEX IX_B_CRM_DP_ENT_HASH_1(ENTITY_TYPE_ID, TYPE_ID, MATCH_HASH, ENTITY_ID, IS_PRIMARY)
);

CREATE TABLE IF NOT EXISTS b_crm_addr(
	TYPE_ID TINYINT(1) UNSIGNED NOT NULL,
	ENTITY_TYPE_ID TINYINT(1) UNSIGNED NOT NULL,
	ENTITY_ID INT(1) UNSIGNED NOT NULL,
	ADDRESS_1 VARCHAR(256),
	ADDRESS_2 VARCHAR(128),
	CITY VARCHAR(128),
	POSTAL_CODE VARCHAR(16),
	REGION VARCHAR(128),
	PROVINCE VARCHAR(128),
	COUNTRY VARCHAR(128),
	COUNTRY_CODE VARCHAR(100),
	PRIMARY KEY(TYPE_ID, ENTITY_TYPE_ID, ENTITY_ID),
	INDEX IX_B_CRM_ADDR_1(ENTITY_TYPE_ID, TYPE_ID, ADDRESS_1, ENTITY_ID),
	INDEX IX_B_CRM_ADDR_2(ENTITY_TYPE_ID, TYPE_ID, ADDRESS_2, ENTITY_ID),
	INDEX IX_B_CRM_ADDR_3(ENTITY_TYPE_ID, TYPE_ID, CITY, ENTITY_ID),
	INDEX IX_B_CRM_ADDR_4(ENTITY_TYPE_ID, TYPE_ID, POSTAL_CODE, ENTITY_ID),
	INDEX IX_B_CRM_ADDR_5(ENTITY_TYPE_ID, TYPE_ID, REGION, ENTITY_ID),
	INDEX IX_B_CRM_ADDR_6(ENTITY_TYPE_ID, TYPE_ID, PROVINCE, ENTITY_ID),
	INDEX IX_B_CRM_ADDR_7(ENTITY_TYPE_ID, TYPE_ID, COUNTRY, ENTITY_ID)
);

CREATE TABLE IF NOT EXISTS b_crm_deal_stage_history(
	ID INT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
	TYPE_ID INT(1) UNSIGNED NOT NULL,
	OWNER_ID INT(1) UNSIGNED NOT NULL,
	CREATED_TIME DATETIME NOT NULL,
	CREATED_DATE DATE NULL,
	START_DATE DATE NOT NULL,
	END_DATE DATE NOT NULL,
	PERIOD_YEAR INT(1) UNSIGNED NOT NULL,
	PERIOD_QUARTER INT(1) UNSIGNED NOT NULL,
	PERIOD_MONTH INT(1) UNSIGNED NOT NULL,
	START_PERIOD_YEAR INT(1) UNSIGNED NOT NULL,
	START_PERIOD_QUARTER INT(1) UNSIGNED NOT NULL,
	START_PERIOD_MONTH INT(1) UNSIGNED NOT NULL,
	END_PERIOD_YEAR INT(1) UNSIGNED NOT NULL,
	END_PERIOD_QUARTER INT(1) UNSIGNED NOT NULL,
	END_PERIOD_MONTH INT(1) UNSIGNED NOT NULL,
	RESPONSIBLE_ID INT(1) UNSIGNED NOT NULL,
	STAGE_SEMANTIC_ID VARCHAR(3) NULL,
	STAGE_ID VARCHAR(50) NULL,
	IS_LOST CHAR(1) NULL,
	PRIMARY KEY(ID),
	INDEX IX_B_CRM_DEAL_SHX_1(OWNER_ID, TYPE_ID, ID),
	INDEX IX_B_CRM_DEAL_SHX_2(TYPE_ID, STAGE_ID, START_DATE, RESPONSIBLE_ID, OWNER_ID),
	INDEX IX_B_CRM_DEAL_SHX_3(TYPE_ID, STAGE_ID, END_DATE, RESPONSIBLE_ID, OWNER_ID),
	INDEX IX_B_CRM_DEAL_SHX_4(TYPE_ID, STAGE_ID, CREATED_TIME, RESPONSIBLE_ID, OWNER_ID),
	INDEX IX_B_CRM_DEAL_SHX_5(PERIOD_YEAR, PERIOD_MONTH, RESPONSIBLE_ID, OWNER_ID, START_DATE, END_DATE),
	INDEX IX_B_CRM_DEAL_SHX_6(PERIOD_YEAR, PERIOD_MONTH, STAGE_SEMANTIC_ID, RESPONSIBLE_ID, OWNER_ID, START_DATE, END_DATE),
	INDEX IX_B_CRM_DEAL_SHX_7(PERIOD_YEAR, PERIOD_MONTH, OWNER_ID, START_DATE, END_DATE),
	INDEX IX_B_CRM_DEAL_SHX_8(TYPE_ID, OWNER_ID, END_DATE, START_DATE)
);

CREATE TABLE IF NOT EXISTS b_crm_deal_sum_stat(
	OWNER_ID INT(1) UNSIGNED NOT NULL,
	CREATED_DATE DATE NOT NULL,
	START_DATE DATE NOT NULL,
	END_DATE DATE NOT NULL,
	PERIOD_YEAR INT(1) UNSIGNED NOT NULL,
	PERIOD_QUARTER INT(1) UNSIGNED NOT NULL,
	PERIOD_MONTH INT(1) UNSIGNED NOT NULL,
	PERIOD_DAY INT(1) UNSIGNED NOT NULL,
	RESPONSIBLE_ID INT(1) UNSIGNED NOT NULL,
	STAGE_SEMANTIC_ID VARCHAR(3) NULL,
	STAGE_ID VARCHAR(50) NULL,
	IS_LOST CHAR(1) NULL,
	CURRENCY_ID CHAR(3) NULL,
	SUM_TOTAL DECIMAL(18,2) NULL,
	UF_SUM_1 DECIMAL(18,2) NULL,
	UF_SUM_2 DECIMAL(18,2) NULL,
	UF_SUM_3 DECIMAL(18,2) NULL,
	UF_SUM_4 DECIMAL(18,2) NULL,
	UF_SUM_5 DECIMAL(18,2) NULL,
	UF_ATTR_1 INT NULL,
	PRIMARY KEY(OWNER_ID, CREATED_DATE),
	INDEX IX_B_CRM_DEAL_SSTAT_1(STAGE_SEMANTIC_ID, OWNER_ID, END_DATE, START_DATE, CREATED_DATE, RESPONSIBLE_ID),
	INDEX IX_B_CRM_DEAL_SSTAT_2(IS_LOST, OWNER_ID, END_DATE, START_DATE, CREATED_DATE, RESPONSIBLE_ID)
);

CREATE TABLE IF NOT EXISTS b_crm_deal_inv_stat(
	OWNER_ID INT(1) UNSIGNED NOT NULL,
	CREATED_DATE DATE NOT NULL,
	START_DATE DATE NOT NULL,
	END_DATE DATE NOT NULL,
	PERIOD_YEAR INT(1) UNSIGNED NOT NULL,
	PERIOD_QUARTER INT(1) UNSIGNED NOT NULL,
	PERIOD_MONTH INT(1) UNSIGNED NOT NULL,
	PERIOD_DAY INT(1) UNSIGNED NOT NULL,
	RESPONSIBLE_ID INT(1) UNSIGNED NOT NULL,
	STAGE_SEMANTIC_ID VARCHAR(3) NULL,
	STAGE_ID VARCHAR(50) NULL,
	IS_LOST CHAR(1) NULL,
	CURRENCY_ID CHAR(3) NULL,
	INVOICE_SUM DECIMAL(18,2) NULL,
	INVOICE_QTY INT(1) UNSIGNED NULL,
	TOTAL_INVOICE_SUM DECIMAL(18,2) NULL,
	TOTAL_INVOICE_QTY INT(1) UNSIGNED NULL,
	TOTAL_SUM DECIMAL(18,2) NULL,
	TOTAL_OWED DECIMAL(18,2) NULL,
	UF_ATTR_1 INT NULL,
	PRIMARY KEY(OWNER_ID, CREATED_DATE),
	INDEX IX_B_CRM_DEAL_ISTAT_1(STAGE_SEMANTIC_ID, OWNER_ID, END_DATE, START_DATE, CREATED_DATE, RESPONSIBLE_ID),
	INDEX IX_B_CRM_DEAL_ISTAT_2(IS_LOST, OWNER_ID, END_DATE, START_DATE, CREATED_DATE, RESPONSIBLE_ID)
);

CREATE TABLE IF NOT EXISTS b_crm_deal_act_stat(
	OWNER_ID INT(1) UNSIGNED NOT NULL,
	DEADLINE_DATE DATE NOT NULL,
	DEADLINE_YEAR INT(1) UNSIGNED NOT NULL,
	DEADLINE_QUARTER INT(1) UNSIGNED NOT NULL,
	DEADLINE_MONTH INT(1) UNSIGNED NOT NULL,
	DEADLINE_DAY INT(1) UNSIGNED NOT NULL,
	RESPONSIBLE_ID INT(1) UNSIGNED NOT NULL,
	STAGE_SEMANTIC_ID VARCHAR(3) NULL,
	STAGE_ID VARCHAR(50) NULL,
	IS_LOST CHAR(1) NULL,
	CALL_QTY INT(1) UNSIGNED NULL,
	MEETING_QTY INT(1) UNSIGNED NULL,
	EMAIL_QTY INT(1) UNSIGNED NULL,
	UF_ATTR_1 INT NULL,
	PRIMARY KEY(OWNER_ID, DEADLINE_DATE),
	INDEX IX_B_CRM_DEAL_ASTAT_1(RESPONSIBLE_ID, DEADLINE_DATE, OWNER_ID, CALL_QTY, MEETING_QTY, EMAIL_QTY),
	INDEX IX_B_CRM_DEAL_ASTAT_2(DEADLINE_DATE, OWNER_ID, CALL_QTY, MEETING_QTY, EMAIL_QTY)
);


