<?
$PERM["extranet"]["11"]="T_8";
$PERM["extranet"]["15"]="T_10";
$PERM["extranet"]["14"]="T_8";
$PERM["extranet"]["13"]="T_8";
$PERM["extranet"]["*"]="D";
$PERM["upload"]["13"]="T_8";
$PERM["upload"]["*"]="R";
$PERM["/"]["12"]="T_10";
$PERM["/"]["11"]="R";
$PERM["/"]["*"]="D";
$PERM["/"]["2"]="D";
$PERM["about"]["8"]="T_9";
$PERM["company"]["8"]="T_9";
$PERM["desktop_app"]["*"]="R";
?>